spring:
    datasource:
        url: jdbc:mysql://theaterproject-db:3306/theaterproject
        username: theater
        password: P@ssw0rd
    jpa:
        hibernate:
            ddl-auto: create-drop #none,create,create-drop,update,validate
        show-sql: true
        properties:
            dialect: org.hibernate.dialect.MySQLDialect
    http:
        multipart:
            enabled: true 
            max-file-size: 10MB
            max-request-size: 10MB

security:
    oauth2:
        client:
            client-id: theater
            client-secret: P@ssw0rd
        token-timeout: 3600
